//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverImage {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResEverImage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResEverImage() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EverImage.ResEverImage", typeof(ResEverImage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ダウンロードが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompletedDownloading {
            get {
                return ResourceManager.GetString("CompletedDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像の取得が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompletedGettingImages {
            get {
                return ResourceManager.GetString("CompletedGettingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompletedSending {
            get {
                return ResourceManager.GetString("CompletedSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}のダウンロードに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DownloadingError {
            get {
                return ResourceManager.GetString("DownloadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evernote に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EndGettingEvernoteInfo {
            get {
                return ResourceManager.GetString("EndGettingEvernoteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evernoteの情報取得に失敗しました。接続状況を確認して下さい。接続に問題がない場合、再ログインをしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedGettingEvernoteUserName {
            get {
                return ResourceManager.GetString("FailedGettingEvernoteUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evernote(情報を取得中です) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GettingEvernoteInfo {
            get {
                return ResourceManager.GetString("GettingEvernoteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Webページから画像を取得中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GettingImagesFromWeb {
            get {
                return ResourceManager.GetString("GettingImagesFromWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}としてEvernoteにログインしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoginToEvernote {
            get {
                return ResourceManager.GetString("LoginToEvernote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evernoteにログインしていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogoutFromEvernote {
            get {
                return ResourceManager.GetString("LogoutFromEvernote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}画像中、{1}画像のダウンロードが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressOfDownloading {
            get {
                return ResourceManager.GetString("ProgressOfDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}画像中、{1}画像の送信が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressOfSending {
            get {
                return ResourceManager.GetString("ProgressOfSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダが指定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectedNoFolder {
            get {
                return ResourceManager.GetString("SelectedNoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectFolderTitle {
            get {
                return ResourceManager.GetString("SelectFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の送信に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendingError {
            get {
                return ResourceManager.GetString("SendingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evernoteに画像を送信中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SendingToEvernote {
            get {
                return ResourceManager.GetString("SendingToEvernote", resourceCulture);
            }
        }
    }
}
